version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    groups:
      gradle-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/plugin-core/chat-ui"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    groups:
      chat-ui-npm:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/plugin-core/js-tests"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    groups:
      js-tests-npm:
        patterns:
          - "*"
