package com.github.catatafishen.ideagentforcopilot.bridge;

import com.intellij.openapi.diagnostic.Logger;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Prepends plugin instructions to an agent-specific config file before the agent process starts.
 *
 * <p>Some agents (e.g. Copilot CLI) ignore the MCP {@code instructions} field from the initialize
 * response and instead read instructions from a config file at a well-known path. This class
 * handles the file-mutation workaround for those agents. The target path is specified per-profile
 * via {@link com.github.catatafishen.ideagentforcopilot.services.AgentProfile#getPrependInstructionsTo()}.</p>
 *
 * <p>Thread-safe: uses a class-level lock so concurrent calls don't race.</p>
 */
public final class InstructionsManager {

    private static final Logger LOG = Logger.getInstance(InstructionsManager.class);

    /** Sentinel used to detect a prior prepend and avoid duplicating instructions. */
    public static final String INSTRUCTIONS_SENTINEL =
        "---\n> ⚙️ Auto-generated by AgentBridge — do not edit this section";
    private static final String INSTRUCTIONS_END =
        "> End of auto-generated instructions\n---";

    private static final Object LOCK = new Object();

    private InstructionsManager() {
    }

    /**
     * Ensures plugin instructions are prepended to {@code relativeTargetPath} inside the project.
     * Safe to call multiple times — uses a sentinel comment to detect a prior prepend.
     *
     * @param projectBasePath absolute path to the project root, or null to skip
     * @param relativeTargetPath path relative to the project root (e.g. {@code ".copilot/copilot-instructions.md"})
     */
    public static void ensureInstructions(@Nullable String projectBasePath,
                                          @NotNull String relativeTargetPath) {
        if (projectBasePath == null || relativeTargetPath.isEmpty()) return;

        synchronized (LOCK) {
            try {
                Path targetFile = Path.of(projectBasePath, relativeTargetPath);
                String pluginInstructions = loadPluginInstructions();

                if (Files.isRegularFile(targetFile)) {
                    String existing = Files.readString(targetFile, StandardCharsets.UTF_8);
                    if (existing.contains(INSTRUCTIONS_SENTINEL)) {
                        return; // already prepended
                    }
                    Files.writeString(targetFile, pluginInstructions + "\n\n" + existing, StandardCharsets.UTF_8);
                    LOG.info("Prepended plugin instructions to " + targetFile);
                } else {
                    Path parent = targetFile.getParent();
                    if (parent != null) {
                        Files.createDirectories(parent);
                    }
                    Files.writeString(targetFile, pluginInstructions, StandardCharsets.UTF_8);
                    LOG.info("Created " + targetFile + " with plugin instructions");
                }
            } catch (IOException e) {
                LOG.warn("Failed to ensure instructions in " + relativeTargetPath, e);
            }
        }
    }

    @NotNull
    private static String loadPluginInstructions() {
        try (InputStream is = InstructionsManager.class.getResourceAsStream("/default-startup-instructions.md")) {
            if (is != null) {
                String instructions = new String(is.readAllBytes(), StandardCharsets.UTF_8);
                return INSTRUCTIONS_SENTINEL + "\n\n" + instructions + "\n\n" + INSTRUCTIONS_END;
            }
        } catch (IOException e) {
            LOG.warn("Failed to load default-startup-instructions.md", e);
        }
        return INSTRUCTIONS_SENTINEL + "\n\nYou are running inside an IntelliJ IDEA plugin with IDE tools.\n\n" + INSTRUCTIONS_END;
    }
}
